version: 1

gate:
  block_severities:
    - critical
    - high

  warn_severities:
    - medium

rules:
  docker.root-user: block
  docker.unpinned-base-image: warn

  github-actions.write-all-permissions: block
  github-actions.unpinned-action: warn
  github-actions.pull-request-target: warn

  secrets.aws-access-key: block
  secrets.github-token: block
  secrets.private-key: block

  terraform.world-open-ipv4: block
  terraform.world-open-ipv6: block
  terraform.public-ip: warn
  terraform.public-read-acl: block

  kubernetes.privileged-container: block
  kubernetes.host-network: block
  kubernetes.host-pid: block
  kubernetes.run-as-non-root: warn
  kubernetes.unpinned-image: warn
